import { ChangeDetectionStrategy, Component, inject, model } from '@angular/core';
import { PasswordPolicyStore } from '../account/password-policy.store';
import { PasswordRulesComponent } from '../account/password-rules.component';

export type PasswordMode = 'generate' | 'set';

/**
 * How an admin gives an account a password (M26, epic decision 2): generated by the server (shown once) or typed,
 * with the policy as live checks; and whether the user must choose their own at the next sign-in.
 */
@Component({
  selector: 'sf-admin-password-choice',
  standalone: true,
  imports: [PasswordRulesComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <fieldset class="choice">
      <legend class="choice__legend">Password</legend>
      <label class="choice__option">
        <input type="radio" name="password-mode" value="generate" [checked]="mode() === 'generate'" (change)="mode.set('generate')" />
        Generate a password
      </label>
      <label class="choice__option">
        <input type="radio" name="password-mode" value="set" [checked]="mode() === 'set'" (change)="mode.set('set')" />
        Set a password
      </label>
      @if (mode() === 'set') {
        <input
          class="choice__input"
          type="password"
          autocomplete="new-password"
          aria-label="New password"
          [value]="password()"
          (input)="password.set($any($event.target).value)"
        />
        <sf-password-rules [policy]="policyStore.policy()" [password]="password()" />
      }
      <label class="choice__option">
        <input type="checkbox" [checked]="mustChange()" (change)="mustChange.set($any($event.target).checked)" />
        Must change password at the next sign-in
      </label>
    </fieldset>
  `,
  styleUrl: './admin-password-choice.component.scss',
})
export class AdminPasswordChoiceComponent {
  protected readonly policyStore = inject(PasswordPolicyStore);

  readonly mode = model<PasswordMode>('generate');
  readonly password = model('');
  readonly mustChange = model(true);

  constructor() {
    this.policyStore.load();
  }
}
