import { ChangeDetectionStrategy, Component, computed, inject, input, output, signal } from '@angular/core';
import { TranslocoPipe, TranslocoService } from '@jsverse/transloco';
import { ApiClient } from '../../core/api/api.client';
import type { components } from '../../core/api/generated/schema.d.ts';
import { problemOf } from '../../core/api/problem.util';
import { ToastService } from '../../core/ui/toast.service';
import { SfDialogComponent, SfDialogFooterDirective } from '../../shared/components/dialog/sf-dialog.component';
import { SfCopyableComponent } from '../../shared/components/display/sf-copyable.component';
import { SfInputComponent } from '../../shared/components/forms/sf-input.component';
import { SfRadioGroupComponent, SfRadioOption } from '../../shared/components/forms/sf-radio-group.component';
import { SfSelectComponent, SfSelectOption } from '../../shared/components/forms/sf-select.component';
import { SfBannerComponent } from '../../shared/components/layout/sf-banner.component';
import { SfButtonComponent } from '../../shared/components/sf-button.component';
import { SfFieldComponent } from '../../shared/components/sf-field.component';
import { PasswordPolicyStore } from '../account/password-policy.store';
import { SYSTEM_ROLES, SystemRole } from './admin-user.util';

type AdminUserDetail = components['schemas']['AdminUserDetail'];
type PasswordChoice = 'generate' | 'set';
type Field = 'username' | 'email' | 'displayName' | 'password';

const USERNAME = /^[a-z0-9._-]{3,}$/;
const EMAIL = /^\S+@\S+\.\S+$/;

/**
 * The user dialog of Administration (M35.16): **New user** (`mode="create"`) and **Reset password** (`mode="reset"`).
 * The password is generated by the server — and then shown once, in a second step, with a copy button — or typed. The
 * generated password lives only in this dialog and is dropped when it closes. Errors show inline after the first submit;
 * a refusal from the server (a taken username, the password policy) lands under its field.
 */
@Component({
  selector: 'sf-admin-user-dialog',
  standalone: true,
  imports: [
    SfBannerComponent,
    SfButtonComponent,
    SfCopyableComponent,
    SfDialogComponent,
    SfDialogFooterDirective,
    SfFieldComponent,
    SfInputComponent,
    SfRadioGroupComponent,
    SfSelectComponent,
    TranslocoPipe,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './admin-user-dialog.component.html',
  styleUrl: './admin-user-dialog.component.scss',
})
export class AdminUserDialogComponent {
  readonly mode = input.required<'create' | 'reset'>();
  /** The user whose password is reset. */
  readonly user = input<AdminUserDetail | null>(null);
  /** The account exists (after its generated password was shown, if any). */
  readonly created = output<AdminUserDetail>();
  /** The password was reset (after the generated one was shown, if any). */
  readonly resetDone = output<AdminUserDetail>();
  readonly closed = output<void>();

  private readonly api = inject(ApiClient);
  private readonly toasts = inject(ToastService);
  private readonly transloco = inject(TranslocoService);
  private readonly policy = inject(PasswordPolicyStore);

  protected readonly username = signal('');
  protected readonly email = signal('');
  protected readonly displayName = signal('');
  protected readonly role = signal<SystemRole>('USER');
  protected readonly choice = signal<PasswordChoice>('generate');
  protected readonly password = signal('');
  protected readonly attempted = signal(false);
  protected readonly submitting = signal(false);
  protected readonly serverErrors = signal<Partial<Record<Field, string>>>({});
  protected readonly failure = signal<string | null>(null);
  /** The one-time password after a successful submit (the second step), and the account it belongs to. */
  protected readonly issuedPassword = signal<string | null>(null);
  private issuedFor: AdminUserDetail | null = null;

  protected readonly minPassword = computed(() => Math.max(1, this.policy.policy()?.minLength ?? 12));

  protected readonly roleOptions = computed<SfSelectOption<SystemRole>[]>(() =>
    SYSTEM_ROLES.map((value) => ({ value, label: this.t(`enum.systemRole.${value}`) })),
  );
  protected readonly choiceOptions = computed<SfRadioOption<PasswordChoice>[]>(() => [
    { value: 'generate', label: this.t('admin.userdialog.password.generate'), description: this.t('admin.userdialog.password.generateHint') },
    {
      value: 'set',
      label: this.t('admin.userdialog.password.set'),
      description: this.t('admin.userdialog.password.setHint', { min: this.minPassword() }),
    },
  ]);

  protected readonly title = computed(() =>
    this.issuedPassword() !== null
      ? this.t('admin.userdialog.password.issuedTitle')
      : this.mode() === 'create'
        ? this.t('admin.userdialog.createTitle')
        : this.t('admin.userdialog.resetTitle', { name: this.nameOf(this.user()) }),
  );
  protected readonly issuedLead = computed(() =>
    this.t('admin.userdialog.password.issuedLead', {
      name: this.mode() === 'create' ? this.displayName().trim() || this.username().trim() : this.nameOf(this.user()),
    }),
  );
  protected readonly resetLead = computed(() => this.t('admin.userdialog.resetLead', { name: this.nameOf(this.user()) }));

  /** What is wrong with the draft — shown only once the person tried to submit — plus what the server refused. */
  protected readonly errors = computed<Record<Field, string | null>>(() => {
    const server = this.serverErrors();
    if (!this.attempted()) {
      return { username: server.username ?? null, email: server.email ?? null, displayName: server.displayName ?? null, password: server.password ?? null };
    }
    const username = this.username().trim();
    return {
      username:
        server.username ??
        (username === ''
          ? this.t('admin.userdialog.usernameRequired')
          : !USERNAME.test(username)
            ? this.t('admin.userdialog.usernameFormat')
            : null),
      email: server.email ?? (EMAIL.test(this.email().trim()) ? null : this.t('admin.userdialog.emailInvalid')),
      displayName: server.displayName ?? (this.displayName().trim() === '' ? this.t('admin.userdialog.displayNameRequired') : null),
      password:
        server.password ??
        (this.choice() === 'set' && [...this.password()].length < this.minPassword()
          ? this.t('admin.userdialog.password.tooShort', { min: this.minPassword() })
          : null),
    };
  });

  constructor() {
    this.policy.load();
  }

  protected submit(): void {
    this.attempted.set(true);
    this.serverErrors.set({});
    this.failure.set(null);
    const errors = this.errors();
    const create = this.mode() === 'create';
    if ((create && (errors.username || errors.email || errors.displayName)) || errors.password || this.submitting()) {
      return;
    }
    this.submitting.set(true);
    if (create) {
      this.api
        .adminCreateUser({
          username: this.username().trim(),
          email: this.email().trim(),
          displayName: this.displayName().trim(),
          systemRole: this.role(),
          mustChangePassword: true,
          ...(this.choice() === 'generate' ? { generatePassword: true } : { password: this.password() }),
        })
        .subscribe({
          next: (user) => this.done(user, 'admin.userdialog.created'),
          error: (err: unknown) => this.refused(err, 'admin.userdialog.createFailed'),
        });
      return;
    }
    const target = this.user();
    if (target?.id == null) {
      this.submitting.set(false);
      return;
    }
    this.api
      .adminResetPassword(
        target.id,
        this.choice() === 'generate'
          ? { generatePassword: true, mustChangePassword: true }
          : { password: this.password(), mustChangePassword: true },
      )
      .subscribe({
        next: (user) => this.done(user, 'admin.userdialog.resetDone'),
        error: (err: unknown) => this.refused(err, 'admin.userdialog.resetFailed'),
      });
  }

  /** The generated password was handed over: forget it and report the account. */
  protected finish(): void {
    const user = this.issuedFor;
    this.issuedPassword.set(null);
    this.issuedFor = null;
    this.password.set('');
    if (user) {
      this.report(user);
    }
    this.closed.emit();
  }

  private done(updated: AdminUserDetail, toastKey: string): void {
    this.submitting.set(false);
    const { generatedPassword, ...user } = updated;
    this.password.set('');
    if (generatedPassword) {
      this.issuedFor = user;
      this.issuedPassword.set(generatedPassword);
      return;
    }
    this.toasts.show(this.t(toastKey, { name: this.nameOf(user) }), 'success');
    this.report(user);
    this.closed.emit();
  }

  private report(user: AdminUserDetail): void {
    if (this.mode() === 'create') {
      this.created.emit(user);
    } else {
      this.resetDone.emit(user);
    }
  }

  private refused(err: unknown, fallbackKey: string): void {
    this.submitting.set(false);
    const problem = problemOf(err, this.t(fallbackKey));
    if (problem.errors.length > 0) {
      this.serverErrors.set({ password: problem.errors.join(' ') });
    } else if (problem.field && ['username', 'email', 'displayName', 'password'].includes(problem.field)) {
      this.serverErrors.set({ [problem.field as Field]: problem.detail });
    } else {
      this.failure.set(problem.detail);
    }
  }

  private nameOf(user: AdminUserDetail | null): string {
    return user?.displayName || user?.username || '';
  }

  private t(key: string, params?: Record<string, unknown>): string {
    return this.transloco.translate(key, params);
  }
}
